# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boring < Formula
  desc "A boooring cli"
  homepage "http://github.com/humblepengi/boring/"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/humblepengi/boring/releases/v0.0.4/boring_0.0.4_macOS_amd64.tar.gz"
      sha256 "8c6416a70e07f7315a30406a57effdc71a19ce1435398333a7cadd436c1f771c"

      def install
        bin.install "bin/boring"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/humblepengi/boring/releases/v0.0.4/boring_0.0.4_macOS_arm64.tar.gz"
      sha256 "2e11de86dc676b6e02948fe44dd036f4bec77a7011ce1b7c5dc32c64ade0d302"

      def install
        bin.install "bin/boring"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "http://github.com/humblepengi/boring/releases/v0.0.4/boring_0.0.4_linux_armv6.tar.gz"
      sha256 "45de78ed722350ae35f91ab6503787c7abcb8d76bf87e3276d5afaf2ad8e99f8"

      def install
        bin.install "bin/boring"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/humblepengi/boring/releases/v0.0.4/boring_0.0.4_linux_amd64.tar.gz"
      sha256 "da2a13bbe1008d73a569a4171b39166c8774e81ec4689829df9ceba7a3c475eb"

      def install
        bin.install "bin/boring"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/humblepengi/boring/releases/v0.0.4/boring_0.0.4_linux_arm64.tar.gz"
      sha256 "ef5771be6e8fb79b6bf1b2eb6296841f41ffa54445dab7cb8c00a6b9ef4e760b"

      def install
        bin.install "bin/boring"
      end
    end
  end
end
