# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boring < Formula
  desc "A boooring cli"
  homepage "http://github.com/humblepengi/boring/"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/humblepengi/boring/releases/download/v0.0.5/boring_0.0.5_macOS_amd64.tar.gz"
      sha256 "29e7dc10004578faa7cbc9295de5e0745b38b64734ac5e14cdd716b12d507669"

      def install
        bin.install "bin/boring"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/humblepengi/boring/releases/download/v0.0.5/boring_0.0.5_macOS_arm64.tar.gz"
      sha256 "945a0f474fc9c2b126b0e99fc65e49f828d804bd92694414dcdb103ce69587aa"

      def install
        bin.install "bin/boring"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "http://github.com/humblepengi/boring/releases/download/v0.0.5/boring_0.0.5_linux_armv6.tar.gz"
      sha256 "b1390557ba8dd272b25b4c96fe8fb5c1486ff37dd283795486872d58c43888e6"

      def install
        bin.install "bin/boring"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/humblepengi/boring/releases/download/v0.0.5/boring_0.0.5_linux_arm64.tar.gz"
      sha256 "00bec898b8845b303e4e83226a8519c243adeefa5f3d55f58bdbf38320709071"

      def install
        bin.install "bin/boring"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/humblepengi/boring/releases/download/v0.0.5/boring_0.0.5_linux_amd64.tar.gz"
      sha256 "69826672690a9b793b745aff1dc47b73a6ac8f75f828653392737155ddfdaf9f"

      def install
        bin.install "bin/boring"
      end
    end
  end
end
